version: "3"
services:
  app:
    image: bookstore-api
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
