name: Build, Test, and Deploy Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: /tmp/.buildx-cache

      - name: Build Docker image
        run: |
          docker build -t bookstore-api .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 -p 27017:27017 --name bookstore-api bookstore-api

      - name: Wait for Docker container
        run: |
          sleep 10 # Wait for the container to start

      - name: Seed the database
        run: |
          docker exec bookstore-api node seed.js

      - name: Test Create Book
        run: |
          curl -X POST http://localhost:3000/books \
          -H "Content-Type: application/json" \
          -d '{"title": "The Art of Computer Programming", "author": "Donald Knuth", "isbn": "9780201896831", "price": 89.99}' \
          -w "%{http_code}" -o response.log
          grep -q "201" response.log || exit 1

      - name: Test Get All Books
        run: |
          curl -X GET http://localhost:3000/books \
          -w "%{http_code}" -o response.log
          grep -q "200" response.log || exit 1

      - name: Test Get Book by ISBN
        run: |
          curl -X GET http://localhost:3000/books/isbn/9780201896831 \
          -w "%{http_code}" -o response.log
          grep -q "200" response.log || exit 1

      - name: Test Update Book
        run: |
          curl -X PUT http://localhost:3000/books/isbn/9780201896831 \
          -H "Content-Type: application/json" \
          -d '{"price": 99.99}' \
          -w "%{http_code}" -o response.log
          grep -q "200" response.log || exit 1

      - name: Test Delete Book
        run: |
          curl -X DELETE http://localhost:3000/books/isbn/9780201896831 \
          -w "%{http_code}" -o response.log
          grep -q "200" response.log || exit 1

      - name: Stop and remove Docker container
        run: |
          docker stop bookstore-api || true
          docker rm bookstore-api || true
